### ISSUE TITLE
In log file, what does "beta" correspond to?

### ISSUE THREAD

**Issue by timflutre** [genetics-statistics/GEMMA#12] opened 2015-04-07 12:55 UTC
Hi Xiang,
a student of mine is using GEMMA (only univariate LMM for the moment). In the log file, we see the following lines:

```
beta estimate in the null model =   57.4035
se(beta) =   0.504719
```

What does this beta correspond to? Is it the intercept of the model "y = W alpha + Z u + e"? Thus, is it the first element of the alpha vector? Could you specify this in the manual?

Thanks,
Tim

**Comment by wanyuac** [comment] 2016-12-25 06:44
This is confusing to me as well because there should not be a beta coefficient in the null model. Would you explain this output?

Thanks,
Wan

**Comment by pcarbo** [comment] 2017-05-17 21:27
@timflutre @wanyuac Yes, these are the regression coefficients for the covariates; if you do not provide any covariates, I believe that there will be a single beta value giving you the estimated intercept.

**Comment by timflutre** [comment] 2017-05-18 07:24
@pcarbo thanks Peter, by any chance can this be added to the manual to prevent others from asking?

**Comment by pcarbo** [comment] 2017-05-18 12:42
@timflutre Yes, I will leave this issue open so that we remember to do that.

**Comment by pcarbo** [comment] 2017-08-21 20:56
Added explanation for the manual in commit c7cbd8b.

**Comment by Owen-haha** [comment] 2017-08-29 13:58
How about the beta in the output file? Is there any transformation for beta? How to interpret it?

**Comment by pcarbo** [comment] 2017-08-29 15:39
@Owen-haha These would be maximum likelihood estimates (MLE) or the restricted maximum likelihood estimates (REML) of "beta" (the regression coefficient for the genotype) in the LMM model (e.g., see Sec. 1.3.1).

**Comment by Owen-haha** [comment] 2017-08-29 22:59
yep, but I still find it difficult to biologically interpret as effect size. How much effect does a genotype to the phenotype given the beta value? Relatively, the bigger the beta value, the larger the effect size.

**Comment by pcarbo** [comment] 2017-08-30 02:31
@Owen-haha The short answer is that the absolute value of beta is the effect size; and indeed it is related to the log of the odds ratio in logistic regression. The units would depend on how you encode the phenotype and the SNP genotypes. So your intuition is generally correct.

There are more subtle issues about interpreting regression coefficients as effect sizes in an LMM. You may have to sit down and some papers on the topic; there are many (too many), but try starting with [this one](http://doi.org/10.1016/j.tree.2008.10.008).

**Comment by pcarbo** [comment] 2017-08-30 02:39
@Owen-haha I should also add that "proportion of variance in phenotype explained by genotype" (PVE) is usually a more precise and interpretable measure of the "effect size." I find that experimenting with the `lm` function in R is a great way to learn about these concepts; it provides estimates of both the regression coefficients and the PVE.

**Comment by Owen-haha** [comment] 2017-08-30 08:48
@pcarbo Thanks so much! The basic function in R is really a good way to start with. 
I did some readings on LMM, but still hard to interpret the coefficients (let alone effect size). 
I tried to interpret as odds ratio, and there should be transformation because the coefficients contain negative values. But I am not sure what transformation? Log based on e or 2, or others ?
The coding is as below.
 Phenotype: Disease -> 1, Control -> 0
 Genotype: Alternative allele -> 1, Major allele -> 0
 Aim: Modelling the effect of alternative allele on disease 
Then for example 4 independent SNPs had beta estimated as 0.9, 0.5, -0.7 and -0.3. What information can be told from them?

**Comment by xiangzhou** [comment] 2017-08-30 13:12
The beta estimates from LMM is different from that of a logistic regression. But you can translate and calculate an approximated odds ratio from the beta estimates in LMM. Specifically, for the beta/odds ratio transformation, let's first assume the logistic model you are interested in is p(y_i=1)=exp(m+x_i*b)/(exp(m+x_i*b)+1), where m is the intercept, y_i is the phenotype and x_i is the genotype for ith individual, and b is the coefficient. If we use the linear (mixed) model y_i=mu+x_i*beta+e for estimation, then by a Taylor expansion argument, we can obtain mu=exp(m)/(exp(m)+1), beta=exp(m)/(exp(m)+1)^2*b. Therefore, once you get mu and beta estimate from the linear mixed model, you can obtain m=log(mu/(1-mu)) and b=beta/(mu*(1-mu)) estimate in the logistic scale. After that, you can obtain odds ratio as usual. 

If you are using the recent version, the software should output the estimate for mu in the *.log.txt file (the estimate for the intercept). But you can easily get a rough estimate of mu by calculating the case proportion.

**Comment by Owen-haha** [comment] 2017-08-31 13:28
It is much clear now! 
How about the `lmm` model with **covariates**?  Does this relation still hold? 
My intuition is that there could be some differences. Am I right?

**Comment by pcarbo** [comment] 2017-08-31 16:24
@Owen-haha The decsription that Xiang gave is not specific to LMMs---it applies to linear regression more generally. So it would also apply equally to the covariates as well.

**Comment by Owen-haha** [comment] 2017-09-04 06:23
Regarding the `PVE`, only PVE estimate in the null model can be found in the *.log.txt file. Why there is no PVE estimate in the alternative model? Can it be obtained easily by hand? 
In my running, PVE estimate in the null model were high (~0.8) in some cases and low (~0.005) in other cases. Is it safe to apply the `lmm` with these extreme PVE estimate?

**Comment by pcarbo** [comment] 2017-09-04 17:53
> Regarding the PVE, only PVE estimate in the null model can be found in the *.log.txt file. 
> Why there is no PVE estimate in the alternative model? Can it be obtained easily by hand?

Yes, the PVE for a single SNP (assuming no covariates) is

```R
pve <- var(x) * (beta^2 + se^2)/var(y)
```

where `x` is the genotype vector. Note that the estimate and standard error (se) is provided for `-lmm 1` (see Issue #81).

> In my running, PVE estimate in the null model were high (~0.8) in some cases and low (~0.005) in other cases. Is it safe to apply the lmm with these extreme PVE estimate?

Absolutely. It is very common that the PVE estimates will be different for different phenotypes.

> BTW,  can you indicate references for the translation of the estimates in linear regression to the counterparts in logistic regression? Because I  need to provide references in my writing.

@xiangzhou?

**Comment by xiangzhou** [comment] 2017-09-05 10:06
> BTW, can you indicate references for the translation of the estimates in linear regression to the counterparts in logistic regression? Because I need to provide references in my writing.

I am not aware of any references. This is just based on a simple Taylor expansion argument, and I presume you don't need to cite anything for Taylor expansion.

**Comment by pjotrp** [comment] 2017-09-12 02:26
I think we can close this issue.

**Closed** 2017-09-12 13:16 UTC
Labels: documentation, fixed in master branch, support

**Comment by wanyuac** [comment] 2018-05-27 06:27
@pcarbo Could you show a reference for your formula?

`pve <- var(x) * (beta^2 + se^2)/var(y)`

I could not find it out in literature.

**Comment by pcarbo** [comment] 2018-06-10 20:17
@wanyuac No, I don't have this reference, but the numerator in this ratio is simply derived from the second moment of beta multipled by the sample variance of x, which is the variance of the "genetic value". You might be able to find it in quantitative genetics textbook.

**Comment by wanyuac** [comment] 2018-06-28 04:29
Thanks for your reply, @pcarbo , although I am still not clear about this formula. I will search through books to find it out.

**Comment by DuttaAnik** [comment] 2021-05-15 19:49
I was searching for this formula. Thank you for posting it here. Can you please explain from where can I get the values of `var(x)` and `var(y) `?
