### ISSUE TITLE
'gsl: brent.c:202: ERROR: function value is not finite' Error with univariate LMM 

### ISSUE THREAD

**Issue by Anh-Thu-Weber** [genetics-statistics/GEMMA#124] opened 2017-12-19 14:20 UTC
Hi,

I am running gemma with the linux executable; it works fine with for the linear model but there is a bug when I use the univariate linear mixed models (I calculated the relatedness matrix with gemma before)

Here is the error message I get:

gsl: brent.c:202: ERROR: function value is not finite
Default GSL error handler invoked.
srun: error: shi35: task 0: Aborted 

It occurs after reading about 30% of the SNPs

Here is the command that works:
srun gemma.linux -bfile NEW_Pphil24_Onilo  -lm 2 -o test_Pphil24

And here is the one that doesn't work:
srun gemma.linux -bfile NEW_Pphil24_Onilo -k output/Relatedness_Pphil24.cXX.txt -lmm 2 -o Linear_mixed_model_uni2_Pphil24

(the srun is a specific command for the cluster I am using)

Could you help me solve this?

Thanks a lot in advance,

Alexandra

**Comment by pjotrp** [comment] 2017-12-19 16:03
Probably a duplicate of https://github.com/genetics-statistics/GEMMA/issues/57. Please report on https://groups.google.com/forum/#!forum/gemma-discussion instead.

**Closed by pjotrp** 2017-12-19 16:03 UTC
