### ISSUE TITLE
Regression for some architectures (arm64 and mips64el)

### ISSUE THREAD

**Issue by tillea** [genetics-statistics/GEMMA#189] opened 2018-12-19 09:53 UTC
Hi,
there is a [bug report against the Debian packaged version of gemma](https://bugs.debian.org/916835) that the test suite fails on arm64 and mips64el. You can find a [full build log for arm64](https://buildd.debian.org/status/fetch.php?pkg=gemma&arch=arm64&ver=0.98.1%2Bdfsg-1&stamp=1545150736&raw=0) (please see at the end of the log).
The build was fine for gemma version 0.98.0.
Kind regards, Andreas.

**Comment by pjotrp** [comment] 2018-12-19 17:31
Thanks @tillea. It looks like *all* tests segfault which is not good! Do you have access to a test system that reproduces that? If so, a stack trace would be helpful. Alternatively we can just aim for AMD64. I doubt anyone is interested in running Gemma on alternate platforms at this point.

**Comment by tillea** [comment] 2018-12-19 19:21
On Wed, Dec 19, 2018 at 09:31:40AM -0800, Pjotr Prins wrote:
> Thanks @tillea. It looks like *all* tests segfault which is not good!
Yes.  Specifically that the minor version bump caused this - so the issue will probably be in the diff to the previous version.

> Do you have access to a test system that reproduces that? If so, a stack trace would be helpful.
In principle every DD has access to a machine of each architecture.  So I can try my luck with this but I'm not sure when I will manage.

> Alternatively we can just aim for AMD64. I doubt anyone is interested in running Gemma on alternate platforms at this point.
I agree that the current use is mostly AMD64.  However, it might be that the issue is a sign for a general problem which just by chance does not occure on AMD64.  So it might make some sense to track this down also for AMD64 usage.

Kind regards, Andreas.

**Comment by pjotrp** [comment] 2018-12-19 19:33
Alternatively it can be caused by the compiler tool chain. Funny it was working before. That diff should not affect all tests. I'll look if I can do something online somewhere. The Guix project also builds for arm64.

**Comment by pjotrp** [comment] 2020-09-29 12:07
Appears to work, no? If not we should try the new build.

**Comment by mr-c** [comment] 2020-09-29 12:55
@pjotrp the build is failing, it seems: https://buildd.debian.org/status/package.php?p=gemma

**Comment by tillea** [comment] 2020-09-29 13:16
On Tue, Sep 29, 2020 at 05:08:12AM -0700, Pjotr Prins wrote:
> Appears to work, no? If not we should try the new build.
Do you want me to try the patch or should I wait for a release (which I would prefer)?

**Comment by pjotrp** [comment] 2020-09-29 13:48
> @pjotrp the build is failing, it seems: https://buildd.debian.org/status/package.php?p=gemma

I think I fixed that error.

**Comment by pjotrp** [comment] 2020-09-29 13:48
> On Tue, Sep 29, 2020 at 05:08:12AM -0700, Pjotr Prins wrote: Appears to work, no? If not we should try the new build.
> Do you want me to try the patch or should I wait for a release (which I would prefer)?

Let me do a release in the coming week or so. Needs some real life testing.

**Comment by pjotrp** [comment] 2020-09-29 13:49
The travis builds are passing with gcc, cland and on OSX: https://travis-ci.org/github/genetics-statistics/GEMMA

**Comment by tillea** [comment] 2020-09-29 13:51
On Tue, Sep 29, 2020 at 06:49:05AM -0700, Pjotr Prins wrote:
> Let me do a release in the coming week or so. Needs some real life testing.
Perfekt. Andreas.

**Comment by tillea** [comment] 2020-11-10 12:03
Ping?  What about the release with the fixes for the build and the test suite?

**Comment by pjotrp** [comment] 2020-11-10 12:38
What is your schedule. I can probably do next week.

**Comment by tillea** [comment] 2020-11-10 13:48
On Tue, Nov 10, 2020 at 04:38:33AM -0800, Pjotr Prins wrote:
> What is your schedule.

As always - I need it yesterday. ;-) :-P

> I can probably do next week.

That's perfectly fine.

Thanks a lot for your work on several free bioinformatics projects, Andreas.

**Comment by pjotrp** [comment] 2020-11-28 15:30
@tillea a new release of GEMMA. Tests pass on Travis and in Guix.

**Comment by pjotrp** [comment] 2020-11-29 09:40
The travis CI build now includes ARM64 and passes. I think we can close this issue.

**Comment by tillea** [comment] 2020-11-29 10:35
On Sun, Nov 29, 2020 at 01:41:04AM -0800, Pjotr Prins wrote:
> The travis CI build now includes ARM64 and passes. I think we can close this issue.

Every possible Debian architecture has now built successfully:
    https://buildd.debian.org/status/package.php?p=gemma
Thanks a lot for your work on this, Andreas.

**Closed** 2020-11-29 11:02 UTC
Labels: bug
