### ISSUE TITLE
Always getting 'pve estimate =0.99xxx se(pve) =-nan'

### ISSUE THREAD

**Issue by xiekunwhy** [genetics-statistics/GEMMA#26] opened 2016-07-26 11:26 UTC
Hi Xiang,
When I use gemma to perform gwas, I always getting 'pve estimate =0.99xxx se(pve) =-nan', and all results are nan(below). Here is my command line,
gemma -bfile mydata -k output/mydata_kinship.sXX.txt -miss 1 -maf 0.01 -r2 1 -lmm
Is there any wrong with the command line or my input datas (attachment)?
[mydata_kinship.sXX.txt](https://github.com/xiangzhou/GEMMA/files/383675/mydata_kinship.sXX.txt)

[GEMMA_data.zip](https://github.com/xiangzhou/GEMMA/files/383679/GEMMA_data.zip)

1 chr     rs      ps      n_miss  allele1 allele0 af      beta    se      l_remle p_wald
      2 1       483     483     58      T       C       0.121   nan     -nan    1.000000e+05    nan
      3 1       2740    2740    54      A       T       0.386   nan     -nan    1.000000e+05    nan
      4 1       4213    4213    38      G       C       0.140   nan     -nan    1.000000e+05    nan
      5 1       4222    4222    38      C       A       0.402   nan     -nan    1.000000e+05    nan
      6 1       4227    4227    38      T       A       0.189   nan     -nan    1.000000e+05    nan
      7 1       4235    4235    38      T       G       0.378   nan     -nan    1.000000e+05    nan
      8 1       4291    4291    39      A       C       0.185   nan     -nan    1.000000e+05    nan

Best wishes!

**Comment by pcarbo** [comment] 2017-05-15 20:07
@xiekunwhy I was able to reproduce this error using the simpler command:

```bash
gemma -bfile mydata -k mydata_kinship.sXX.txt -lmm
```

Further, I did *not* get an error using the linear regression instead of the LMM:

```bash
gemma  -bfile mydata -k mydata_kinship.sXX.txt -lm
```

The eigenvalue decomposition seemed to work okay (using the `-eigen` flag). 

So my hunch is that GEMMA is behaving strangely with your phenotype data. To test this, I created a "dummy" phenotype (see the attached file), and re-fit the LMM to the dummy data:

```
$ gemma -bfile mydata -k mydata_kinship.sXX.txt -lmm -n 4
Reading Files ... 
## number of total individuals = 120
## number of analyzed individuals = 120
## number of covariates = 1
## number of phenotypes = 1
## number of total SNPs = 361505
## number of analyzed SNPs = 131480
Start Eigen-Decomposition...
pve estimate =0.0863376
se(pve) =0.148312
```

This time, it worked, and produced reasonable estimates.

I noticed that all your phenotype values are either 1 or 2. 

@xiangzhou, do you have any thoughts as to why the LMM might not work with a binary-valued phenotype that is either 1 or 2, and only 120 samples?

[mydata.fam.gz](https://github.com/xiangzhou/GEMMA/files/1002318/mydata.fam.gz)

**Comment by pcarbo** [comment] 2017-05-18 16:26
@xiekunwhy One possible explanation is that the rows of the phenotype and genotype files do not match up. I have seen people make this error before.

**Comment by pjotrp** [comment] 2017-08-03 16:02
We should check whether this is a duplicate of https://github.com/genetics-statistics/GEMMA/issues/58

**Comment by pjotrp** [comment] 2017-08-06 14:53
With gsl1 in both cases we get results in the assoc file . With gsl2 we get nan in the assoc file. In all cases we get se(pve) =-nan for the first fam file. So I think it is mostly a GSL issue.

**Comment by pcarbo** [comment] 2017-08-07 18:28
@xiekunwhy In case this is still useful for you, the new GEMMA v0.96 binaries should solve your problem. See also Issue #58.

**Comment by pcarbo** [comment] 2017-08-07 18:28
@pjotrp Is it okay if I close this issue? Based on your test it looks like we solved the issue.

**Comment by xiekunwhy** [comment] 2017-08-07 23:08
OK，thanks you two.

**Comment by pjotrp** [comment] 2017-08-08 14:56
Please reopen if you still see a problem.

**Comment by pjotrp** [comment] 2017-08-20 07:39
Running the test with my latest checks

```
    $gemma -bfile data/issue26/mydata -k data/issue26/mydata_kinship.sXX.txt \
           -miss 1 -maf 0.01 -r2 1 -lmm \
           -debug -issue 26 \
           -o $outn
```

we now get

```
testIssue26
Reading Files ... 
## number of total individuals = 120
## number of analyzed individuals = 120
## number of covariates = 1
## number of phenotypes = 1
## number of total SNPs    = 361505
## number of analyzed SNPs = 361505
**** DEBUG: Validating K in src/debug.cpp at line 23 in void do_validate_K(const gsl_matrix*, bool, const char*, int)
**** WARNING: K has small or negative eigenvalues! in src/gemma.cpp at line 2720
**** DEBUG: Eigenvalues Min 1.72861e-15 Max 11.9122 Ratio 6.89122e+15
**** WARNING: K is ill conditioned! in src/gemma.cpp at line 2720
**** FAIL: K is not positive definite! in src/gemma.cpp at line 2720

```

So, it looks like the Kinship matrix is a problem.

**Comment by pcarbo** [comment] 2017-08-21 17:18
Based on followup discussion, this may not necessarily be an issue because the centered relatedness matrix is expected to have one zero eigenvalue. More to come---

**Comment by pjotrp** [comment] 2017-09-12 02:25
Yes, the centered relatedness has one zero eigen value. Reporting is fixed now. Please reopen if you encounter issues again.

**Closed by pjotrp** 2017-09-12 02:25 UTC
Labels: support
